### ISSUE TITLE
Crash with "minifyEnabled true"

### ISSUE THREAD

**Issue by irinaminakova** [CappasityTech/CappasityAndroid#4]
The following message is partially wrong, please read the next one.
------------------------------------------------------
Hello! We had a problem with Cappasity when adding fragment dynamically via FragmentManager and loading Cappasity model in onViewCreated() of this fragment. (When loading model from onResume(), it works fine.) The crash was only on Xiaomi devices (Android 7 and Android 9) 
Here is stack trace:
```
Fatal Exception: java.lang.NullPointerException
Attempt to read from field 'java.lang.String d.a.a.a.c.b.d.a.b.a' on a null object reference
a.a.a.a.b.b.c.a.invokeSuspend (a.java:7)
kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith (BaseContinuationImpl.java:33)
kotlinx.coroutines.DispatchedTask.run (DispatchedTask.java:106)
android.os.Handler.handleCallback (Handler.java:754)
android.os.Handler.dispatchMessage (Handler.java:95)
android.os.Looper.loop (Looper.java:163)
android.app.ActivityThread.main (ActivityThread.java:6388)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:930)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:820)
```

This is a piece of code for loading model:
```
override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)
        ...
            modelView.setOnModelLoadListener {
                shown360(true)
            }
            Cappasity.modelService.getModel(
            cappasity.cappasityID,
            onSuccess = { cappasityModel ->
                modelView.loadModel(cappasityModel, cappasity.generateCappasityParams())
                shown360(false)
            },
             onFailure = { cappasityException ->
                 logE(TAG, cappasityException)
                 showErrorDialog()
                 shown360(true)
             }
         )
    }
```

This is a piece of code for adding a fragment containing ModelView:
```
                childFragmentManager.beginTransaction()
                    .add(R.id.productContainer, fragment360)
                    .commit()
```

**Comment by irinaminakova** [comment]
Sorry for the confusion, but the reason for crash is different. The problem is with minifying the release build. You can reproduce this crash in your demo app, if you specify "minifyEnabled true" in demo-kotlin/build.gradle :
`buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.debug
        }
    }`

In this case release build with crash with NullPointerException after you input model id in search field.

**Comment by AlexanderCappasity** [comment]
Please look at our latest release.
[0.4.10](https://github.com/CappasityTech/CappasityAndroid/releases/tag/v0.4.10)

Thank you.
