### ISSUE TITLE
Obfuscated classes "a.a.a..." are in conflict with other libraries

### ISSUE THREAD

**Issue by valeriy-grigoryev** [CappasityTech/CappasityAndroid#5]
The latest version of **cappasity-framework.aar** in conflict with **com.yandex.money:checkout:4.1.0**. The reason for the conflict is that both of these libraries contain the same obfuscated classes without any prefix package. So we get the following error:

```
Duplicate class a.a.a.a.a.a.a found in modules jetified-cappasity-framework-runtime.jar (:cappasity-framework:) and jetified-checkout-4.1.0-runtime.jar (com.yandex.money:checkout:4.1.0)
Duplicate class a.a.a.a.a.b.a found in modules jetified-cappasity-framework-runtime.jar (:cappasity-framework:) and jetified-checkout-4.1.0-runtime.jar (com.yandex.money:checkout:4.1.0)
Duplicate class a.a.a.a.a.c.a found in modules jetified-cappasity-framework-runtime.jar (:cappasity-framework:) and jetified-checkout-4.1.0-runtime.jar (com.yandex.money:checkout:4.1.0)
```

Could you please fix it to resolve the conflicts? (for example move obfuscated classes to the unique root package)

**Comment by valeriy-grigoryev** [comment]
![image](https://user-images.githubusercontent.com/70197582/105856190-fc573080-5ff9-11eb-9c29-c51fcaac74a7.png)

**Comment by npevgova** [comment]
Thank you for indicating the issue. Please try the latest version.
